name: ML-Core
main: ml.minelounge.core.Main
version: 6.9
author: Chaspyr
authors: [Chaspyr, Derkades]
description: Core plugin for the MineLounge server

commands:
  staff:
    description: aisjdm
    